### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by mathiasbynens** [sindresorhus/dog-names#2]
Since the readme says things like “sorted by popularity” and “not accepting PRs for additional names” it seems like the list of names was not just randomly made up or does not consist of your personal favorites or anything like that. So, what is the source for this data? And shouldn’t it be credited in the README?

The same goes for the other `*-names` projects, I guess.

**Comment by kevva** [comment]
https://www.rover.com/blog/dog-names/, although the list used in this module seems to be a little outdated (https://www.rover.com/blog/popular-dog-names-2014/).

**Comment by sindresorhus** [comment]
I don't remember. Should indeed have written it down.
